Public Function portchanger(portcode As String)
Select Case portcode

'- - - - - - - - - L I S T A  K O D O W - - - - - - - - - -
'
' w kolumnie Ports of Arival moga pojawic sie skroty
'
' przykladem jest FXT
'
' ta funkcja zamienia napotkane FXT na inna wybrana nazwe
'
' jesli pojawi sie cos nowego po porstu dopisz linie jak w LISCIE KODOW
'
' pozdro
'
'- - - - - - - - - L I S T A  K O D O W - - - - - - - - - -
    Case "FXT" ' < - - - - - - - - - K O D  Z  I N P U T A
    portcode = "somename" ' < -  N A  C O  Z A M I E N I C

    Case "TEE"
    portcode = "somename"

    Case "STN"
    portcode = "somename"

    Case "FXT"
    portcode = "somename"

    Case "FXT"
    portcode = "somename"

    Case "FXT"
    portcode = "somename"
    
    Case "___"
    portcode = "___"
    
    Case "___"
    portcode = "___"
    
    
    
    
    
    
'- - - - - - - - - L I S T A  K O D O W - - - - - - - - - -




End Select
End Function
